import * as elements from "./elements";
import * as collections from "./collections"
import * as views from "./views"
import * as modules from "./modules"
import { App } from "vue";

function install(app: App) {
  Object.values({
    ...elements,
    ...collections,
    ...views,
    ...modules
  }).map((component) => app.use(component))
}

export default { install };

export { default as SuiButton } from './elements/Button/Button'
export { default as SuiButtonContent } from './elements/Button/ButtonContent'
export { default as SuiButtonGroup } from './elements/Button/ButtonGroup'
export { default as SuiContainer } from './elements/Container/Container'
export { default as SuiDivider } from './elements/Divider/Divider'
export { default as SuiEmoji } from './elements/Emoji/Emoji'
export { default as SuiFlag } from './elements/Flag/Flag'
export { default as SuiHeader } from './elements/Header/Header'
export { default as SuiHeaderContent } from './elements/Header/HeaderContent'
export { default as SuiHeaderSubheader } from './elements/Header/HeaderSubheader'
export { default as SuiIcon } from './elements/Icon/Icon'
export { default as SuiIconGroup } from './elements/Icon/IconGroup'
export { default as SuiImage } from './elements/Image/Image'
export { default as SuiImageGroup } from './elements/Image/ImageGroup'
export { default as SuiInput } from './elements/Input/Input'
export { default as SuiLabel } from './elements/Label/Label'
export { default as SuiLabelDetail } from './elements/Label/LabelDetail'
export { default as SuiLabelGroup } from './elements/Label/LabelGroup'
export { default as SuiList } from './elements/List/List'
export { default as SuiListContent } from './elements/List/ListContent'
export { default as SuiListDescription } from './elements/List/ListDescription'
export { default as SuiListHeader } from './elements/List/ListHeader'
export { default as SuiListIcon } from './elements/List/ListIcon'
export { default as SuiListItem } from './elements/List/ListItem'
export { default as SuiListList } from './elements/List/ListList'
export { default as SuiLoader } from './elements/Loader/Loader'
export { default as SuiRail } from './elements/Rail/Rail'
export { default as SuiReveal } from './elements/Reveal/Reveal'
export { default as SuiRevealContent } from './elements/Reveal/RevealContent'
export { default as SuiSegment } from './elements/Segment/Segment'
export { default as SuiSegmentGroup } from './elements/Segment/SegmentGroup'
export { default as SuiSegmentInline } from './elements/Segment/SegmentInline'
export { default as SuiStep } from './elements/Step/Step'
export { default as SuiStepContent } from './elements/Step/StepContent'
export { default as SuiStepDescription } from './elements/Step/StepDescription'
export { default as SuiStepGroup } from './elements/Step/StepGroup'
export { default as SuiStepTitle } from './elements/Step/StepTitle'

export { default as SuiBreadcrumb } from './collections/Breadcrumb/Breadcrumb'
export { default as SuiBreadcrumbDivider } from './collections/Breadcrumb/BreadcrumbDivider'
export { default as SuiBreadcrumbSection } from './collections/Breadcrumb/BreadcrumbSection'
export { default as SuiForm } from './collections/Form/Form'
export { default as SuiFormField } from './collections/Form/FormField'
export { default as SuiFormGroup } from './collections/Form/FormGroup'
export { default as SuiFormTextarea } from './collections/Form/FormTextarea'
export { default as SuiGrid } from './collections/Grid/Grid'
export { default as SuiGridColumn } from './collections/Grid/GridColumn'
export { default as SuiGridRow } from './collections/Grid/GridRow'
export { default as SuiMenu } from './collections/Menu/Menu'
export { default as SuiMenuHeader } from './collections/Menu/MenuHeader'
export { default as SuiMenuItem } from './collections/Menu/MenuItem'
export { default as SuiMenuMenu } from './collections/Menu/MenuMenu'
export { default as SuiMessage } from './collections/Message/Message'
export { default as SuiMessageContent } from './collections/Message/MessageContent'
export { default as SuiMessageHeader } from './collections/Message/MessageHeader'
export { default as SuiMessageItem } from './collections/Message/MessageItem'
export { default as SuiMessageList } from './collections/Message/MessageList'
export { default as SuiTable } from './collections/Table/Table'
export { default as SuiTableBody } from './collections/Table/TableBody'
export { default as SuiTableCell } from './collections/Table/TableCell'
export { default as SuiTableFooter } from './collections/Table/TableFooter'
export { default as SuiTableHeader } from './collections/Table/TableHeader'
export { default as SuiTableHeaderCell } from './collections/Table/TableHeaderCell'
export { default as SuiTableRow } from './collections/Table/TableRow'

export { default as SuiAdvertisement } from './views/Advertisement/Advertisement'
export { default as SuiCard } from './views/Card/Card'
export { default as SuiCardContent } from './views/Card/CardContent'
export { default as SuiCardDescription} from './views/Card/CardDescription'
export { default as SuiCardGroup } from './views/Card/CardGroup'
export { default as SuiCardHeader } from './views/Card/CardHeader'
export { default as SuiCardMeta } from './views/Card/CardMeta'
export { default as SuiComment } from './views/Comment/Comment'
export { default as SuiCommentAction } from './views/Comment/CommentAction'
export { default as SuiCommentActions } from './views/Comment/CommentActions'
export { default as SuiCommentAuthor } from './views/Comment/CommentAuthor'
export { default as SuiCommentAvatar } from './views/Comment/CommentAvatar'
export { default as SuiCommentContent } from './views/Comment/CommentContent'
export { default as SuiCommentGroup } from './views/Comment/CommentGroup'
export { default as SuiCommentMetadata } from './views/Comment/CommentMetadata'
export { default as SuiCommentText } from './views/Comment/CommentText'
export { default as SuiFeed } from './views/Feed/Feed'
export { default as SuiFeedContent } from './views/Feed/FeedContent'
export { default as SuiFeedDate } from './views/Feed/FeedDate'
export { default as SuiFeedEvent } from './views/Feed/FeedEvent'
export { default as SuiFeedExtra } from './views/Feed/FeedExtra'
export { default as SuiFeedLabel } from './views/Feed/FeedLabel'
export { default as SuiFeedLike } from './views/Feed/FeedLike'
export { default as SuiFeedMeta } from './views/Feed/FeedMeta'
export { default as SuiFeedSummary } from './views/Feed/FeedSummary'
export { default as SuiFeedUser } from './views/Feed/FeedUser'
export { default as SuiItem } from './views/Item/Item'
export { default as SuiItemContent } from './views/Item/ItemContent'
export { default as SuiItemDescription } from './views/Item/ItemDescription'
export { default as SuiItemExtra } from './views/Item/ItemExtra'
export { default as SuiItemGroup } from './views/Item/ItemGroup'
export { default as SuiItemHeader } from './views/Item/ItemHeader'
export { default as SuiItemImage } from './views/Item/ItemImage'
export { default as SuiItemMeta } from './views/Item/ItemMeta'
export { default as SuiStatistic } from './views/Statistic/Statistic'
export { default as SuiStatisticGroup } from './views/Statistic/StatisticGroup'
export { default as SuiStatisticLabel } from './views/Statistic/StatisticLabel'
export { default as SuiStatisticValue } from './views/Statistic/StatisticValue'

export { default as SuiAccordion } from './modules/Accordion/Accordion'
export { default as SuiAccordionAccordion } from './modules/Accordion/AccordionAccordion'
export { default as SuiAccordionContent } from './modules/Accordion/AccordionContent'
export { default as SuiAccordionTab } from './modules/Accordion/AccordionTab'
export { default as SuiAccordionTitle } from './modules/Accordion/AccordionTitle'
export { default as SuiCalendar } from './modules/Calendar/Calendar'
export { default as SuiCheckbox } from './modules/Checkbox/Checkbox'
export { default as SuiDimmer } from './modules/Dimmer/Dimmer'
export { default as SuiDimmerDimmable } from './modules/Dimmer/DimmerDimmable'
export { default as SuiDropdown } from './modules/Dropdown/Dropdown'
export { default as SuiDropdownItem } from './modules/Dropdown/DropdownItem'
export { default as SuiDropdownMenu } from './modules/Dropdown/DropdownMenu'
export { default as SuiEmbed } from './modules/Embed/Embed'
export { default as SuiModal } from './modules/Modal/Modal'
export { default as SuiModalActions } from './modules/Modal/ModalActions'
export { default as SuiModalContent } from './modules/Modal/ModalContent'
export { default as SuiModalDescription } from './modules/Modal/ModalDescription'
export { default as SuiModalHeader } from './modules/Modal/ModalHeader'
export { default as SuiPopup } from './modules/Popup/Popup'
export { default as SuiProgress } from './modules/Progress/Progress'
export { default as SuiRating } from './modules/Rating/Rating'
export { default as SuiSidebar } from './modules/Sidebar/Sidebar'
export { default as SuiSlider } from './modules/Slider/Slider'
export { default as SuiTab } from './modules/Tab/Tab'
export { default as SuiTabPanel } from './modules/Tab/TabPanel'
export { default as SuiTransition } from './modules/Transition/Transition'

export { useToast } from './modules/Toast/useToast'
