import { App } from "vue"

import * as components from './components'

function install(app: App) {
  Object.values({
    ...components,
  }).map((component) => app.use(component))
}

export default { install };

export { default as SuiButton } from './components/Button/Button'
export { default as SuiButtonContent } from './components/Button/ButtonContent'
export { default as SuiButtonGroup } from './components/Button/ButtonGroup'
export { default as SuiContainer } from './components/Container/Container'
export { default as SuiDivider } from './components/Divider/Divider'
export { default as SuiEmoji } from './components/Emoji/Emoji'
export { default as SuiFlag } from './components/Flag/Flag'
export { default as SuiHeader } from './components/Header/Header'
export { default as SuiHeaderContent } from './components/Header/HeaderContent'
export { default as SuiHeaderSubheader } from './components/Header/HeaderSubheader'
export { default as SuiIcon } from './components/Icon/Icon'
export { default as SuiIconGroup } from './components/Icon/IconGroup'
export { default as SuiImage } from './components/Image/Image'
export { default as SuiImageGroup } from './components/Image/ImageGroup'
export { default as SuiInput } from './components/Input/Input'
export { default as SuiLabel } from './components/Label/Label'
export { default as SuiLabelDetail } from './components/Label/LabelDetail'
export { default as SuiLabelGroup } from './components/Label/LabelGroup'
export { default as SuiList } from './components/List/List'
export { default as SuiListContent } from './components/List/ListContent'
export { default as SuiListDescription } from './components/List/ListDescription'
export { default as SuiListHeader } from './components/List/ListHeader'
export { default as SuiListIcon } from './components/List/ListIcon'
export { default as SuiListItem } from './components/List/ListItem'
export { default as SuiListList } from './components/List/ListList'
export { default as SuiLoader } from './components/Loader/Loader'
export { default as SuiRail } from './components/Rail/Rail'
export { default as SuiReveal } from './components/Reveal/Reveal'
export { default as SuiRevealContent } from './components/Reveal/RevealContent'
export { default as SuiSegment } from './components/Segment/Segment'
export { default as SuiSegmentGroup } from './components/Segment/SegmentGroup'
export { default as SuiSegmentInline } from './components/Segment/SegmentInline'
export { default as SuiStep } from './components/Step/Step'
export { default as SuiStepContent } from './components/Step/StepContent'
export { default as SuiStepDescription } from './components/Step/StepDescription'
export { default as SuiStepGroup } from './components/Step/StepGroup'
export { default as SuiStepTitle } from './components/Step/StepTitle'

export { default as SuiBreadcrumb } from './components/Breadcrumb/Breadcrumb'
export { default as SuiBreadcrumbDivider } from './components/Breadcrumb/BreadcrumbDivider'
export { default as SuiBreadcrumbSection } from './components/Breadcrumb/BreadcrumbSection'
export { default as SuiForm } from './components/Form/Form'
export { default as SuiFormField } from './components/Form/FormField'
export { default as SuiFormGroup } from './components/Form/FormGroup'
export { default as SuiFormTextarea } from './components/Form/FormTextarea'
export { default as SuiGrid } from './components/Grid/Grid'
export { default as SuiGridColumn } from './components/Grid/GridColumn'
export { default as SuiGridRow } from './components/Grid/GridRow'
export { default as SuiMenu } from './components/Menu/Menu'
export { default as SuiMenuHeader } from './components/Menu/MenuHeader'
export { default as SuiMenuItem } from './components/Menu/MenuItem'
export { default as SuiMenuMenu } from './components/Menu/MenuMenu'
export { default as SuiMessage } from './components/Message/Message'
export { default as SuiMessageContent } from './components/Message/MessageContent'
export { default as SuiMessageHeader } from './components/Message/MessageHeader'
export { default as SuiMessageItem } from './components/Message/MessageItem'
export { default as SuiMessageList } from './components/Message/MessageList'
export { default as SuiTable } from './components/Table/Table'
export { default as SuiTableBody } from './components/Table/TableBody'
export { default as SuiTableCell } from './components/Table/TableCell'
export { default as SuiTableFooter } from './components/Table/TableFooter'
export { default as SuiTableHeader } from './components/Table/TableHeader'
export { default as SuiTableHeaderCell } from './components/Table/TableHeaderCell'
export { default as SuiTableRow } from './components/Table/TableRow'

export { default as SuiAdvertisement } from './components/Advertisement/Advertisement'
export { default as SuiCard } from './components/Card/Card'
export { default as SuiCardContent } from './components/Card/CardContent'
export { default as SuiCardDescription} from './components/Card/CardDescription'
export { default as SuiCardGroup } from './components/Card/CardGroup'
export { default as SuiCardHeader } from './components/Card/CardHeader'
export { default as SuiCardMeta } from './components/Card/CardMeta'
export { default as SuiComment } from './components/Comment/Comment'
export { default as SuiCommentAction } from './components/Comment/CommentAction'
export { default as SuiCommentActions } from './components/Comment/CommentActions'
export { default as SuiCommentAuthor } from './components/Comment/CommentAuthor'
export { default as SuiCommentAvatar } from './components/Comment/CommentAvatar'
export { default as SuiCommentContent } from './components/Comment/CommentContent'
export { default as SuiCommentGroup } from './components/Comment/CommentGroup'
export { default as SuiCommentMetadata } from './components/Comment/CommentMetadata'
export { default as SuiCommentText } from './components/Comment/CommentText'
export { default as SuiFeed } from './components/Feed/Feed'
export { default as SuiFeedContent } from './components/Feed/FeedContent'
export { default as SuiFeedDate } from './components/Feed/FeedDate'
export { default as SuiFeedEvent } from './components/Feed/FeedEvent'
export { default as SuiFeedExtra } from './components/Feed/FeedExtra'
export { default as SuiFeedLabel } from './components/Feed/FeedLabel'
export { default as SuiFeedLike } from './components/Feed/FeedLike'
export { default as SuiFeedMeta } from './components/Feed/FeedMeta'
export { default as SuiFeedSummary } from './components/Feed/FeedSummary'
export { default as SuiFeedUser } from './components/Feed/FeedUser'
export { default as SuiItem } from './components/Item/Item'
export { default as SuiItemContent } from './components/Item/ItemContent'
export { default as SuiItemDescription } from './components/Item/ItemDescription'
export { default as SuiItemExtra } from './components/Item/ItemExtra'
export { default as SuiItemGroup } from './components/Item/ItemGroup'
export { default as SuiItemHeader } from './components/Item/ItemHeader'
export { default as SuiItemImage } from './components/Item/ItemImage'
export { default as SuiItemMeta } from './components/Item/ItemMeta'
export { default as SuiStatistic } from './components/Statistic/Statistic'
export { default as SuiStatisticGroup } from './components/Statistic/StatisticGroup'
export { default as SuiStatisticLabel } from './components/Statistic/StatisticLabel'
export { default as SuiStatisticValue } from './components/Statistic/StatisticValue'

export { default as SuiAccordion } from './components/Accordion/Accordion'
export { default as SuiAccordionAccordion } from './components/Accordion/AccordionAccordion'
export { default as SuiAccordionContent } from './components/Accordion/AccordionContent'
export { default as SuiAccordionTab } from './components/Accordion/AccordionTab'
export { default as SuiAccordionTitle } from './components/Accordion/AccordionTitle'
export { default as SuiCalendar } from './components/Calendar/Calendar'
export { default as SuiCheckbox } from './components/Checkbox/Checkbox'
export { default as SuiDimmer } from './components/Dimmer/Dimmer'
export { default as SuiDimmerDimmable } from './components/Dimmer/DimmerDimmable'
export { default as SuiDropdown } from './components/Dropdown/Dropdown'
export { default as SuiDropdownItem } from './components/Dropdown/DropdownItem'
export { default as SuiDropdownMenu } from './components/Dropdown/DropdownMenu'
export { default as SuiEmbed } from './components/Embed/Embed'
export { default as SuiModal } from './components/Modal/Modal'
export { default as SuiModalActions } from './components/Modal/ModalActions'
export { default as SuiModalContent } from './components/Modal/ModalContent'
export { default as SuiModalDescription } from './components/Modal/ModalDescription'
export { default as SuiModalHeader } from './components/Modal/ModalHeader'
export { default as SuiPopup } from './components/Popup/Popup'
export { default as SuiProgress } from './components/Progress/Progress'
export { default as SuiRating } from './components/Rating/Rating'
export { default as SuiSidebar } from './components/Sidebar/Sidebar'
export { default as SuiSlider } from './components/Slider/Slider'
export { default as SuiTab } from './components/Tab/Tab'
export { default as SuiTabPanel } from './components/Tab/TabPanel'
export { default as SuiTransition } from './components/Transition/Transition'

export { useToast } from './components/Toast/useToast'
